### PR TITLE
Rewrite match clause to avoid eagerness after initial variable

### PR DESCRIPTION
**Pull request by ghcooper**

### CODE REVIEW

**Comment by samth** [comment]
The semantics of that match code was not supposed to have changed. Can you give an example of what went wrong?

**Comment by ghcooper** [comment]
It looks like "and" no longer short-circuits:

> (match empty
    [(and lst (app cons? lst) (app first lst)) 'foo]
    [_ 'bar])

>>> first: contract violation
  expected: (and/c list? (not/c empty?))
  given: '()

**Comment by ghcooper** [comment]
My mistake on two counts. The example I gave didn't make sense, and the short-circuiting behavior only seems to change when the first term in the "and" pattern is a variable:

(define (recip n)
  (/ 1 n))

(define (my-fun x)
  (match (sub1 x)
    [(and (? positive?) (app recip 1/3) y) y]
    [_ 'foo]))

(my-fun 1) => 'foo

And similarly if the binding "y" falls between the other two clauses. But:

(define (my-fun x)
  (match (sub1 x)
    [(and y (? positive?) (app recip 1)) y]
    [_ 'foo]))

(my-fun 1) => division-by-zero

**Comment by samth** [comment]
This is a bug in `match`, I'd say. I'll work on a fix. 
For the moment, you can write the pattern as `(? signal? (? signal-stale? dep))`

**Comment by samth** [comment]
This is entirely a bug in `match`: I have specific code in the `match` pattern compiler that's intended to preserve order in `and` clauses, so this shouldn't ever happen.

I've also invited you to be a member of the Racket group, which will allow you to commit this in the meantime.

**Pull request merged**
